# Default initial positions for robot's ros2_control fake system

initial_positions:
  chassis_joint: 0
  head_platform_pitch_joint: 0
  head_platform_roll_joint: 0
  head_platform_yaw_joint: 0
  left_arm_elbow_joint: 0
  left_arm_rotator_joint: 0
  left_arm_shoulder_joint: 0
  left_ear_pitch_joint: 0
  left_ear_rotator_joint: 0
  right_arm_elbow_joint: 0
  right_arm_rotator_joint: 0
  right_arm_shoulder_joint: 0
  right_ear_pitch_joint: 0
  right_ear_rotator_joint: 0