FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y python3-pip

COPY ./scripts/install_rosdeps.sh install_rosdeps.sh
RUN \
    . /opt/ros/humble/setup.sh && \
    apt-get update && rosdep update && ./install_rosdeps.sh

RUN mkdir -p /ros_ws
WORKDIR /ros_ws

COPY . .

RUN . /opt/ros/humble/setup.sh && \
    colcon build --merge-install --continue-on-error \
    --cmake-args \
    -DCMAKE_BUILD_TYPE=Release
