name: bearmax builder

on:
  - workflow_dispatch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  docker_image_name: torrentofshame/bearmax

jobs:
  build:
    name: "Build Docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./ros_ws
          file: ./ros_ws/Dockerfile.ros
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: "${{ env.docker_image_name }}:latest"
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
      - name: Save Docker Image
        run: |
          docker save -o bearmax.img "${{ env.docker_image_name }}:ros-base"
      - name: Upload Image artifact
        uses: actions/upload-artifact@v3
        with:
          name: bearmax.img
          path: bearmax.img

